/**
 * Mock service data for development and testing
 * Simulates realistic macOS service data
 */

import type { Service, SystemExtension } from "../types";

export function getMockServices(): Service[] {
	const services: Service[] = [
		// System Daemons (Apple)
		{
			id: "system-com.apple.launchd.peruser",
			label: "com.apple.launchd.peruser",
			displayName: "peruser",
			type: "LaunchDaemon",
			domain: "system",
			status: "running",
			pid: 1,
			protection: "immutable",
			plistPath: "/System/Library/LaunchDaemons/com.apple.launchd.peruser.plist",
			enabled: true,
			isAppleService: true,
			requiresRoot: true,
		},
		{
			id: "system-com.apple.mDNSResponder",
			label: "com.apple.mDNSResponder",
			displayName: "mDNSResponder",
			type: "LaunchDaemon",
			domain: "system",
			status: "running",
			pid: 142,
			protection: "sip-protected",
			plistPath: "/System/Library/LaunchDaemons/com.apple.mDNSResponder.plist",
			description: "Multicast DNS and Service Discovery",
			enabled: true,
			isAppleService: true,
			requiresRoot: true,
		},
		{
			id: "system-com.apple.opendirectoryd",
			label: "com.apple.opendirectoryd",
			displayName: "opendirectoryd",
			type: "LaunchDaemon",
			domain: "system",
			status: "running",
			pid: 89,
			protection: "sip-protected",
			plistPath: "/System/Library/LaunchDaemons/com.apple.opendirectoryd.plist",
			description: "Open Directory Service",
			enabled: true,
			isAppleService: true,
			requiresRoot: true,
		},
		{
			id: "system-com.apple.securityd",
			label: "com.apple.securityd",
			displayName: "securityd",
			type: "LaunchDaemon",
			domain: "system",
			status: "running",
			pid: 78,
			protection: "sip-protected",
			plistPath: "/System/Library/LaunchDaemons/com.apple.securityd.plist",
			description: "Security Server",
			enabled: true,
			isAppleService: true,
			requiresRoot: true,
		},
		{
			id: "system-com.apple.fseventsd",
			label: "com.apple.fseventsd",
			displayName: "fseventsd",
			type: "LaunchDaemon",
			domain: "system",
			status: "running",
			pid: 56,
			protection: "sip-protected",
			plistPath: "/System/Library/LaunchDaemons/com.apple.fseventsd.plist",
			description: "File System Events Daemon",
			enabled: true,
			isAppleService: true,
			requiresRoot: true,
		},

		// Third-party Daemons
		{
			id: "system-com.docker.vmnetd",
			label: "com.docker.vmnetd",
			displayName: "vmnetd",
			type: "LaunchDaemon",
			domain: "system",
			status: "running",
			pid: 512,
			protection: "normal",
			plistPath: "/Library/LaunchDaemons/com.docker.vmnetd.plist",
			description: "Docker VM Network Daemon",
			enabled: true,
			isAppleService: false,
			requiresRoot: true,
		},
		{
			id: "system-org.postgresql.postgres",
			label: "org.postgresql.postgres",
			displayName: "postgres",
			type: "LaunchDaemon",
			domain: "system",
			status: "stopped",
			protection: "normal",
			plistPath: "/Library/LaunchDaemons/org.postgresql.postgres.plist",
			description: "PostgreSQL Database Server",
			enabled: false,
			isAppleService: false,
			requiresRoot: true,
		},
		{
			id: "system-com.microsoft.autoupdate.helper",
			label: "com.microsoft.autoupdate.helper",
			displayName: "autoupdate.helper",
			type: "LaunchDaemon",
			domain: "system",
			status: "stopped",
			exitStatus: 0,
			protection: "normal",
			plistPath: "/Library/LaunchDaemons/com.microsoft.autoupdate.helper.plist",
			description: "Microsoft AutoUpdate Helper",
			enabled: true,
			isAppleService: false,
			requiresRoot: true,
		},
		{
			id: "system-com.adobe.agsservice",
			label: "com.adobe.agsservice",
			displayName: "agsservice",
			type: "LaunchDaemon",
			domain: "system",
			status: "running",
			pid: 1024,
			protection: "normal",
			plistPath: "/Library/LaunchDaemons/com.adobe.agsservice.plist",
			description: "Adobe Genuine Software Service",
			enabled: true,
			isAppleService: false,
			requiresRoot: true,
		},
		{
			id: "system-org.nginx.daemon",
			label: "org.nginx.daemon",
			displayName: "nginx",
			type: "LaunchDaemon",
			domain: "system",
			status: "error",
			exitStatus: 1,
			protection: "normal",
			plistPath: "/Library/LaunchDaemons/org.nginx.daemon.plist",
			description: "Nginx HTTP Server",
			lastError: "Configuration file error",
			enabled: true,
			isAppleService: false,
			requiresRoot: true,
		},

		// User LaunchAgents (Apple)
		{
			id: "user-com.apple.Spotlight",
			label: "com.apple.Spotlight",
			displayName: "Spotlight",
			type: "LaunchAgent",
			domain: "user",
			status: "running",
			pid: 456,
			protection: "system-owned",
			plistPath: "/System/Library/LaunchAgents/com.apple.Spotlight.plist",
			description: "Spotlight Search",
			enabled: true,
			isAppleService: true,
			requiresRoot: false,
		},
		{
			id: "user-com.apple.notificationcenterui",
			label: "com.apple.notificationcenterui",
			displayName: "notificationcenterui",
			type: "LaunchAgent",
			domain: "user",
			status: "running",
			pid: 789,
			protection: "system-owned",
			plistPath: "/System/Library/LaunchAgents/com.apple.notificationcenterui.plist",
			description: "Notification Center",
			enabled: true,
			isAppleService: true,
			requiresRoot: false,
		},
		{
			id: "user-com.apple.Dock.agent",
			label: "com.apple.Dock.agent",
			displayName: "Dock.agent",
			type: "LaunchAgent",
			domain: "user",
			status: "running",
			pid: 234,
			protection: "system-owned",
			plistPath: "/System/Library/LaunchAgents/com.apple.Dock.agent.plist",
			description: "macOS Dock",
			enabled: true,
			isAppleService: true,
			requiresRoot: false,
		},

		// User LaunchAgents (Third-party)
		{
			id: "user-com.docker.helper",
			label: "com.docker.helper",
			displayName: "docker.helper",
			type: "LaunchAgent",
			domain: "user",
			status: "running",
			pid: 1567,
			protection: "normal",
			plistPath: "~/Library/LaunchAgents/com.docker.helper.plist",
			description: "Docker Desktop Helper",
			enabled: true,
			isAppleService: false,
			requiresRoot: false,
		},
		{
			id: "user-com.google.keystone.agent",
			label: "com.google.keystone.agent",
			displayName: "keystone.agent",
			type: "LaunchAgent",
			domain: "user",
			status: "running",
			pid: 2048,
			protection: "normal",
			plistPath: "~/Library/LaunchAgents/com.google.keystone.agent.plist",
			description: "Google Software Update",
			enabled: true,
			isAppleService: false,
			requiresRoot: false,
		},
		{
			id: "user-homebrew.mxcl.redis",
			label: "homebrew.mxcl.redis",
			displayName: "redis",
			type: "LaunchAgent",
			domain: "user",
			status: "stopped",
			protection: "normal",
			plistPath: "~/Library/LaunchAgents/homebrew.mxcl.redis.plist",
			description: "Redis Server (Homebrew)",
			enabled: false,
			isAppleService: false,
			requiresRoot: false,
		},
		{
			id: "user-homebrew.mxcl.mysql",
			label: "homebrew.mxcl.mysql",
			displayName: "mysql",
			type: "LaunchAgent",
			domain: "user",
			status: "running",
			pid: 3456,
			protection: "normal",
			plistPath: "~/Library/LaunchAgents/homebrew.mxcl.mysql.plist",
			description: "MySQL Server (Homebrew)",
			enabled: true,
			isAppleService: false,
			requiresRoot: false,
		},
		{
			id: "user-com.dropbox.DropboxMacUpdate.agent",
			label: "com.dropbox.DropboxMacUpdate.agent",
			displayName: "DropboxMacUpdate",
			type: "LaunchAgent",
			domain: "user",
			status: "disabled",
			protection: "normal",
			plistPath: "~/Library/LaunchAgents/com.dropbox.DropboxMacUpdate.agent.plist",
			description: "Dropbox Update Service",
			enabled: false,
			isAppleService: false,
			requiresRoot: false,
		},
		{
			id: "user-com.1password.agent",
			label: "com.1password.agent",
			displayName: "1password.agent",
			type: "LaunchAgent",
			domain: "user",
			status: "running",
			pid: 890,
			protection: "normal",
			plistPath: "~/Library/LaunchAgents/com.1password.agent.plist",
			description: "1Password Browser Extension Helper",
			enabled: true,
			isAppleService: false,
			requiresRoot: false,
		},
	];

	// Add System Extensions
	const systemExtensions: SystemExtension[] = [
		{
			id: "sysext-com.apple.DriverKit.AppleUSBNetworking",
			label: "com.apple.DriverKit.AppleUSBNetworking",
			displayName: "AppleUSBNetworking",
			type: "SystemExtension",
			domain: "system",
			status: "running",
			protection: "sip-protected",
			bundleId: "com.apple.DriverKit.AppleUSBNetworking",
			teamId: "APPLE",
			version: "1.0",
			state: "activated_enabled",
			categories: ["com.apple.system_extension.driver_extension"],
			enabled: true,
			isAppleService: true,
			requiresRoot: true,
		},
		{
			id: "sysext-com.crowdstrike.falcon.Agent",
			label: "com.crowdstrike.falcon.Agent",
			displayName: "Falcon Agent",
			type: "SystemExtension",
			domain: "system",
			status: "running",
			protection: "normal",
			bundleId: "com.crowdstrike.falcon.Agent",
			teamId: "X9E956P446",
			version: "6.45.0",
			state: "activated_enabled",
			categories: ["com.apple.system_extension.endpoint_security"],
			enabled: true,
			isAppleService: false,
			requiresRoot: true,
		},
		{
			id: "sysext-com.docker.vmnetd.network",
			label: "com.docker.vmnetd.network",
			displayName: "Docker Network",
			type: "SystemExtension",
			domain: "system",
			status: "running",
			protection: "normal",
			bundleId: "com.docker.vmnetd.network",
			teamId: "9BNSXJN65R",
			version: "4.23.0",
			state: "activated_enabled",
			categories: ["com.apple.system_extension.network_extension"],
			enabled: true,
			isAppleService: false,
			requiresRoot: true,
		},
		{
			id: "sysext-com.nordvpn.macos.tun-provider",
			label: "com.nordvpn.macos.tun-provider",
			displayName: "NordVPN TUN",
			type: "SystemExtension",
			domain: "system",
			status: "stopped",
			protection: "normal",
			bundleId: "com.nordvpn.macos.tun-provider",
			teamId: "W5W395V82Z",
			version: "8.1.0",
			state: "activated_waiting",
			categories: ["com.apple.system_extension.network_extension"],
			enabled: true,
			isAppleService: false,
			requiresRoot: true,
		},
	];

	return [...services, ...systemExtensions];
}
